[package]
name = "cache-service-rust"
version = "0.1.0"
authors = ["Rogi Solorzano <rogi.solorzano@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
serde_json = "1.0"